### ISSUE TITLE
您好， 这个项目模型用到的数据集能发下吗，谢谢啦

### ISSUE THREAD

**Issue by liwenqiang1** [wjwABCDEFG/BetaFish-WQPS#1]

**Comment by liwenqiang1** [comment]
您好， 这个项目模型用到的数据集能发下吗，谢谢啦

**Comment by wjwABCDEFG** [comment]
这个是我们学校水产学院历年的数据，请问是用作什么用途呢？其实数据库结构可以在WQMS工程下查看到（https://github.com/wjwABCDEFG/BetaFish-WQMS/tree/main/src/main/java/cn/edu/gdou/wqms/model），根据结构完全足以替换成自己的数据集就可以用作训练

**Comment by liwenqiang1** [comment]
收到，感谢回复!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wjwABCDEFG/BetaFish-WQPS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wjwABCDEFG/BetaFish-WQPS] 您好， 这个项目模型用到的数据集能发下吗，谢谢啦 (Issue #1)





 
这个是我们学校水产学院历年的数据，请问是用作什么用途呢？其实数据库结构可以在WQMS工程下查看到（https://github.com/wjwABCDEFG/BetaFish-WQMS/tree/main/src/main/java/cn/edu/gdou/wqms/model），根据结构完全足以替换成自己的数据集就可以用作训练
